# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Arthur/Faculdade/2021.1/Sistemas_Digitais_para_Computadores_A/Projetos_Vivado/Neander/neanderv2/neanderv2.srcs/sources_1/ip/memoria/memoria.xci
# IP: The module: 'memoria' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Arthur/Faculdade/2021.1/Sistemas_Digitais_para_Computadores_A/Projetos_Vivado/Neander/neanderv2/neanderv2.srcs/sources_1/ip/memoria/memoria_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'memoria'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Arthur/Faculdade/2021.1/Sistemas_Digitais_para_Computadores_A/Projetos_Vivado/Neander/neanderv2/neanderv2.srcs/sources_1/ip/memoria/memoria.xci
# IP: The module: 'memoria' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Arthur/Faculdade/2021.1/Sistemas_Digitais_para_Computadores_A/Projetos_Vivado/Neander/neanderv2/neanderv2.srcs/sources_1/ip/memoria/memoria_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'memoria'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
